#include "syscall.h"
#include "traps.h"

#define SYSCALL(name) \
  .globl name; \
  name: \
    movl $SYS_ ## name, %eax; \
    int $T_SYSCALL; \
    ret

SYSCALL(fork)
SYSCALL(exit)
SYSCALL(wait)
SYSCALL(pipe)
SYSCALL(read)
SYSCALL(write)
SYSCALL(close)
SYSCALL(kill)
SYSCALL(exec)
SYSCALL(open)
SYSCALL(mknod)
SYSCALL(unlink)
SYSCALL(fstat)
SYSCALL(link)
SYSCALL(mkdir)
SYSCALL(chdir)
SYSCALL(dup)
SYSCALL(getpid)
SYSCALL(sbrk)
SYSCALL(sleep)
SYSCALL(uptime)
#ifdef GETPPID
SYSCALL(getppid)
#endif // GETPPID
#ifdef CPS
SYSCALL(cps)
#endif // CPS

SYSCALL(kdebug)
SYSCALL(halt)

#ifdef KTHREADS
//# error You need to extern the sys_kthread calls here
//#endif // KTHREADS

//#ifdef KTHREADS1

SYSCALL(kthread_create)
SYSCALL(kthread_join)
SYSCALL(kthread_exit)

#endif //KTHREADS1
